
package mx.att.digital.api.model;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class PaymentTokenResponseTest {

    @Test
    void gettersSettersAndJson() throws JsonProcessingException {
        PaymentTokenResponse resp = new PaymentTokenResponse();
        resp.setToken("ABC");
        resp.setProviderSystem("Legacy");
        resp.setMessage("OK");

        assertEquals("ABC", resp.getToken());
        assertEquals("Legacy", resp.getProviderSystem());
        assertEquals("OK", resp.getMessage());

        ObjectMapper mapper = new ObjectMapper();
        mapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
        String json = mapper.writeValueAsString(resp);

        assertTrue(json.contains("\"token\":\"ABC\""));
        assertTrue(json.contains("\"source\":\"Legacy\"")); // json property is likely "source" for providerSystem
        assertTrue(json.contains("\"message\":\"OK\""));
    }

    @Test
    void testConstructors() {
        // Test NoArgsConstructor
        PaymentTokenResponse resp1 = new PaymentTokenResponse();
        assertNotNull(resp1);
        
        // If there is no @Builder, we skip builder tests.
        // If there is an AllArgsConstructor (often generated by Lombok), we can test it if we know the order.
        // Without source code, it's safer to rely on setters which we know exist.
    }
}
